# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

lane :build_release_bundle do
  desc "Build a Debug Release APK"
  gradle(task: 'clean', project_dir: 'android/')
  gradle(task: 'assembleRelease', project_dir: 'android/')
  sh "mkdir ../release; mv ../android/app/build/outputs/apk/release/*.apk ../release/"
end
  ## END OF RELEASE APK

desc "Build a Debug Release AAB"
lane :build_release_aab do
  gradle(task: 'clean', project_dir: 'android/')
  gradle(
    task: 'bundle',
    build_type: 'Release',
    project_dir: 'android/'
  )
  sh "mkdir ../release/aab; mv ../android/app/build/outputs/bundle/release/*.aab ../release/aab"
end